api_platform:
    title: Test Quiz service
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]
    exception_to_status:
        Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
