security:
    providers:
        jwt:
            lexik_jwt:
                class: App\Entity\User
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER]
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        api:
            #pattern: ^/vehicle-service/
            stateless: true
            anonymous: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator