name: CI/CD

on:
  push:
  pull_request:

env:
  DOCKER_BUILDX_VERSION: '0.4.1'
  DOCKER_COMPOSE_VERSION: '1.25.4'
  DOCKER_REGISTRY: quay.io
  APP_ENV: test 

jobs:
  phpunit:
     name: PhpUnit
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: Run docker compose
         run: docker-compose -f docker-compose.yml up -d --build
       - name: Check containers
         run: docker ps
       - name: Wait for PHP
         uses: jakejarvis/wait-action@master
         with:
           time: '20s'
       - name: Run PHPUnit tests
         run: docker-compose exec -T php composer test-coverage
         
  ct-lint:
    name: ct lint (ct ${{ matrix.ct }})
    runs-on: ubuntu-latest
    container:
      image: quay.io/helmpack/chart-testing:v${{ matrix.ct }}
    strategy:
      matrix:
        ct:
          - '2.4.0'
      fail-fast: false
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: ct lint --all --chart-dirs api/helm/api
